//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace My_Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Shop_Phong_StartEntities : DbContext
    {
        public Shop_Phong_StartEntities()
            : base("name=Shop_Phong_StartEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Loai_San_Pham> Loai_San_Pham { get; set; }
        public DbSet<San_Pham> San_Pham { get; set; }
        public DbSet<ThongTinKhachHang> ThongTinKhachHangs { get; set; }
    }
}
