//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace My_Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class San_Pham
    {
        public int Ma_San_Pham { get; set; }
        public Nullable<int> ID_Loai_San_Pham { get; set; }
        public string Ten_San_Pham { get; set; }
        public string Hinh_Anh { get; set; }
        public string Thong_Tin_San_Pham { get; set; }
        public Nullable<double> Gia_tien { get; set; }
    
        public virtual Loai_San_Pham Loai_San_Pham { get; set; }
    }
}
